sudo: required

language: c

services:
    - docker

before_install:
    - docker build -t twippy_docker .

#script:
#    - docker run --rm -v ${PWD}:/home/twippy/Workspace -w /home/twippy/Workspace -i -t twippy_docker arm-none-eabi-gcc --version && make clean && make
